"""GitHub publisher — creates repos and pushes generated projects."""

import os
from pathlib import Path
from typing import Optional
from github import Github
from github.GithubException import GithubException

from .config import ToolSmithConfig


class GitHubPublisher:
    """Publishes generated projects to GitHub under GrooveXlabs."""
    
    def __init__(self, config: ToolSmithConfig):
        self.config = config
        self.github = Github(config.github_token)
        self.user = self.github.get_user()
        self.org = self.github.get_organization(config.groovex_org)
    
    def publish(
        self,
        project_dir: str,
        repo_name: Optional[str] = None,
        private: bool = False,
        description: Optional[str] = None
    ) -> str:
        """
        Publish a project directory to GitHub.
        
        Args:
            project_dir: Local path to generated project
            repo_name: Target repo name (default: directory name)
            private: Whether repo should be private
            description: Repo description
            
        Returns:
            URL of created repository
        """
        project_path = Path(project_dir)
        repo_name = repo_name or project_path.name
        
        # Ensure valid repo name
        repo_name = repo_name.lower().replace(" ", "-").replace("_", "-")
        
        # Check if repo exists
        try:
            existing = self.org.get_repo(repo_name)
            print(f"Warning: Repo {repo_name} already exists. Creating with timestamp...")
            repo_name = f"{repo_name}-{int(os.time())}"
        except GithubException:
            pass
        
        # Create repo
        description = description or f"Generated by ToolSmith — {repo_name}"
        repo = self.org.create_repo(
            name=repo_name,
            description=description,
            private=private,
            auto_init=False,
            has_issues=True,
            has_wiki=False,
            has_projects=False
        )
        
        # Upload files
        self._upload_files(repo, project_path)
        
        return repo.html_url
    
    def _upload_files(self, repo, project_path: Path, base_path: str = ""):
        """Recursively upload files to the repository."""
        for item in sorted(project_path.iterdir()):
            relative_path = f"{base_path}/{item.name}" if base_path else item.name
            
            if item.name == ".git":
                continue
                
            if item.is_dir():
                self._upload_files(repo, item, relative_path)
            else:
                content = item.read_text(encoding="utf-8")
                try:
                    repo.create_file(
                        path=relative_path,
                        message=f"Add {relative_path}",
                        content=content
                    )
                except GithubException as e:
                    if e.status == 422:
                        # File might exist, try updating
                        try:
                            contents = repo.get_contents(relative_path)
                            repo.update_file(
                                path=relative_path,
                                message=f"Update {relative_path}",
                                content=content,
                                sha=contents.sha
                            )
                        except Exception:
                            print(f"Warning: Could not upload {relative_path}")
                    else:
                        print(f"Warning: Could not upload {relative_path}: {e}")
